name: "Node App CI"
run-name: "Testing the Node App"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: "Testing the App with Jest"
    strategy:
      matrix:
        node-version: ["18.x", "20.x", "21.x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --fronze-lockfile
      - run: yarn prepare
      - run: yarn test

  publish:
    name: "Build a Docker image and publish to DockerHub"
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.tag }}
