name: "Node App CI"
run-name: "Testing the Node App"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: jest-test
        uses: ./.github/actions/node-app-test.yml
