name: "Node App CI"
run-name: "Testing the Node App"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    strategy:
      matrix:
        node-version: ["18.x", "20.x", "21.x"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile
      - run: yarn test
